apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mq-qm01
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mq/environments/dev/mq-qm01
    targetRevision: master
    repoURL: https://github.com/ibmclientengineering/multi-tenancy-gitops-apps.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
