apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: createcustomer-barauth
spec:
  secretName: createcustomer-barauth-vcjb9
  type: barauth
  version: 13.0.8.0-r1
---
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-serverconf
spec:
  contents: RGVmYXVsdHM6CiAgcG9saWN5UHJvamVjdDogJ2NyZWF0ZS1jdXN0b21lci1wb2xpY3knCg==
  type: serverconf
  version: 13.0.8.0-r1
---
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  contents: UEsDBAoAAAAAADJx51wAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAAxBrTWoQa01qdXgLAAEE9QEAAAQAAAAAUEsDBBQAAAAIADJx51wyw5h4pAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADEGtNahBrTWp1eAsAAQT1AQAABAAAAABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLAwQUAAAACAAycedcqrMvdpAAAADDAAAAKAAcAGNyZWF0ZS1jdXN0b21lci1wb2xpY3kvcG9saWN5LmRlc2NyaXB0b3JVVAkAAxBrTWoQa01qdXgLAAEE9QEAAAQAAAAAfY27DsIwDAD3fkWUnRgYEKr6WBAzA3wATU0baOLIjgj8PRHszHe6a/qXX9QTWRyFVm/MWisMlkYXplZfzsfVXvdd1QTZ1pEWZ98npjvadECx7GIiVqUQpC5Gq+eUYg2QczZu8MaShy+FyDRCxkHijIzgUeQ64cD0QIadKV/45XVXKdUw3ooWLAqUOfy5d9UHUEsBAh4DCgAAAAAAMnHnXAAAAAAAAAAAAAAAABcAGAAAAAAAAAAQAO1BAAAAAGNyZWF0ZS1jdXN0b21lci1wb2xpY3kvVVQFAAMQa01qdXgLAAEE9QEAAAQAAAAAUEsBAh4DFAAAAAgAMnHnXDLDmHikAAAA8gAAACsAGAAAAAAAAQAAAKSBUQAAAGNyZWF0ZS1jdXN0b21lci1wb2xpY3kvYmFja2VuZHVybC5wb2xpY3l4bWxVVAUAAxBrTWp1eAsAAQT1AQAABAAAAABQSwECHgMUAAAACAAycedcqrMvdpAAAADDAAAAKAAYAAAAAAABAAAApIFaAQAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9wb2xpY3kuZGVzY3JpcHRvclVUBQADEGtNanV4CwABBPUBAAAEAAAAAFBLBQYAAAAAAwADADwBAABMAgAAAAA=
  type: policyproject
  version: 13.0.8.0-r1
---
