apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: createcustomer
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  license:
    accept: true
    license: L-RJGW-BUAA2R
    use: CloudPakForIntegrationNonProductionFREE
  version: '13.0'
  replicas: 1
  barURL:
    - http://ace-bar.tools.svc/createcustomer.bar
  configurations:
    - createcustomer-barauth
    - create-customer-serverconf
    - create-customer-policy

